### EDA and Data Lookup

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(r"C:\Portfolio-Projects\Job-Description-Analysis\data\raw\Job_descriptions_v2.csv")
df.head(5)

,id,role,type,job_desc,year,qualification,experience,tech_skills,soft_skills
0,1,AI Engineer,Internship,"Final year students / recent graduates in CS, ...",2026,Bachelors,0,"Python, ML, LangChain, Hugging Face, OpenAI API","Communication, Problem Solving"
1,2,AI Engineer,Internship,Proficiency in Python and comfort working with...,2026,Bachelors,0,"Python, APIs, LLMs, Prompt Engineering, LangCh...","Communication, Problem Solving"
2,3,AI Engineer,Internship,Strong interest in AI and a willingness to lea...,2026,Bachelors,0,"Python, Javascript, React, Full Stack, APIs, M...","Communication, Problem Solving"
3,4,AI Engineer,Senior,6+ years full-stack software engineering exper...,2026,NaN,5-10,"Python, Javascript, React, Full Stack, SQL, AP...","Communication, Problem Solving"
4,5,AI Engineer,Junior,"AI/ML models, Python, Core ML concepts, ML fra...",2026,Bachelors,0-1,"Python, ML, TensorFlow/PyTorch, Scikit-Learn, ...","Communication, Problem Solving"

### EDA

In [3]:
df.isna().count()

id               324
role             324
type             324
job_desc         324
year             324
qualification    324
experience       324
tech_skills      324
soft_skills      324
dtype: int64

In [4]:
df.describe()

               id    year
count  324.000000   324.0
mean   159.845679  2026.0
std     90.064825     0.0
min      1.000000  2026.0
25%     82.750000  2026.0
50%    163.500000  2026.0
75%    235.250000  2026.0
max    316.000000  2026.0

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 324 entries, 0 to 323
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             324 non-null    int64
 1   role           324 non-null    str
 2   type           324 non-null    str
 3   job_desc       324 non-null    str
 4   year           324 non-null    int64
 5   qualification  270 non-null    str
 6   experience     324 non-null    str
 7   tech_skills    324 non-null    str
 8   soft_skills    300 non-null    str
dtypes: int64(2), str(7)
memory usage: 22.9 KB

In [6]:
df.fillna('Not Specified', inplace=True).head(5)

,id,role,type,job_desc,year,qualification,experience,tech_skills,soft_skills
0,1,AI Engineer,Internship,"Final year students / recent graduates in CS, ...",2026,Bachelors,0,"Python, ML, LangChain, Hugging Face, OpenAI API","Communication, Problem Solving"
1,2,AI Engineer,Internship,Proficiency in Python and comfort working with...,2026,Bachelors,0,"Python, APIs, LLMs, Prompt Engineering, LangCh...","Communication, Problem Solving"
2,3,AI Engineer,Internship,Strong interest in AI and a willingness to lea...,2026,Bachelors,0,"Python, Javascript, React, Full Stack, APIs, M...","Communication, Problem Solving"
3,4,AI Engineer,Senior,6+ years full-stack software engineering exper...,2026,Not Specified,5-10,"Python, Javascript, React, Full Stack, SQL, AP...","Communication, Problem Solving"
4,5,AI Engineer,Junior,"AI/ML models, Python, Core ML concepts, ML fra...",2026,Bachelors,0-1,"Python, ML, TensorFlow/PyTorch, Scikit-Learn, ...","Communication, Problem Solving"

In [7]:
df.nunique()

id               314
role               4
type               3
job_desc         319
year               1
qualification      4
experience         7
tech_skills      285
soft_skills       32
dtype: int64

In [8]:
role_unique = df['role'].unique()
print(role_unique)

<StringArray>
['AI Engineer', 'AI Developer', 'Software Engineer', 'Software Developer']
Length: 4, dtype: str

In [9]:
type_unique = df['type'].unique()
print(type_unique)

<StringArray>
['Internship', 'Senior', 'Junior']
Length: 3, dtype: str

In [10]:
experience_unique = df['experience'].unique()
print(experience_unique)

<StringArray>
['0', '5-10', '0-1', '1-5', '15+', '10-15', '0-2']
Length: 7, dtype: str

In [11]:
df.to_csv("C:\\Portfolio-Projects\\Job-Description-Analysis\\data\\clean\\v2\\cleaned_job_descriptions_v2.csv", index=False)