### EDA and Data Lookup

In [107]:
import pandas as pd

In [108]:
df = pd.read_csv(r"C:\Portfolio-Projects\Job-Description-Analysis\data\raw\Job_descriptions.csv")
df.head(5)

,id,role,type,job_desc,year,qualification,experience,tech_skills,soft_skills
0,1,AI Engineer,Internship,"Final year students / recent graduates in CS, ...",2026,Bachelors,0,"Python, ML, LangChain, Hugging Face, OpenAI API","Communication, Problem Solving"
1,2,AI Engineer,Internship,Proficiency in Python and comfort working with...,2026,Bachelors,0,"Python, APIs, LLMs, Prompt Engineering, LangCh...","Communication, Problem Solving"
2,3,AI Engineer,Internship,Strong interest in AI and a willingness to lea...,2026,Bachelors,0,"Python, Javascript, React, Full Stack, APIs, M...","Communication, Problem Solving"
3,4,AI Engineer,Senior,6+ years full-stack software engineering exper...,2026,NaN,5-10,"Python, Javascript, React, Full Stack, SQL, AP...","Communication, Problem Solving"
4,5,AI Engineer,Junior,"AI/ML models, Python, Core ML concepts, ML fra...",2026,Bachelors,0-1,"Python, ML, TensorFlow/PyTorch, Scikit-Learn, ...","Communication, Problem Solving"

### EDA

In [109]:
df.isna().count()

id               29
role             29
type             29
job_desc         29
year             29
qualification    29
experience       29
tech_skills      29
soft_skills      29
dtype: int64

In [110]:
df.describe()

              id    year
count  29.000000    29.0
mean   15.241379  2026.0
std     8.842491     0.0
min     1.000000  2026.0
25%     8.000000  2026.0
50%    15.000000  2026.0
75%    22.000000  2026.0
max    30.000000  2026.0

In [111]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 29 entries, 0 to 28
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             29 non-null     int64
 1   role           29 non-null     str
 2   type           29 non-null     str
 3   job_desc       29 non-null     str
 4   year           29 non-null     int64
 5   qualification  21 non-null     str
 6   experience     29 non-null     str
 7   tech_skills    29 non-null     str
 8   soft_skills    29 non-null     str
dtypes: int64(2), str(7)
memory usage: 27.3 KB

In [112]:
df.fillna('Not Specified', inplace=True).head(5)

,id,role,type,job_desc,year,qualification,experience,tech_skills,soft_skills
0,1,AI Engineer,Internship,"Final year students / recent graduates in CS, ...",2026,Bachelors,0,"Python, ML, LangChain, Hugging Face, OpenAI API","Communication, Problem Solving"
1,2,AI Engineer,Internship,Proficiency in Python and comfort working with...,2026,Bachelors,0,"Python, APIs, LLMs, Prompt Engineering, LangCh...","Communication, Problem Solving"
2,3,AI Engineer,Internship,Strong interest in AI and a willingness to lea...,2026,Bachelors,0,"Python, Javascript, React, Full Stack, APIs, M...","Communication, Problem Solving"
3,4,AI Engineer,Senior,6+ years full-stack software engineering exper...,2026,Not Specified,5-10,"Python, Javascript, React, Full Stack, SQL, AP...","Communication, Problem Solving"
4,5,AI Engineer,Junior,"AI/ML models, Python, Core ML concepts, ML fra...",2026,Bachelors,0-1,"Python, ML, TensorFlow/PyTorch, Scikit-Learn, ...","Communication, Problem Solving"

In [113]:
df.nunique()

id               29
role              2
type              3
job_desc         29
year              1
qualification     3
experience        5
tech_skills      29
soft_skills       3
dtype: int64

In [114]:
role_unique = df['role'].unique()
print(role_unique)

<ArrowStringArray>
['AI Engineer', 'AI Developer']
Length: 2, dtype: str

In [115]:
type_unique = df['type'].unique()
print(type_unique)

<ArrowStringArray>
['Internship', 'Senior', 'Junior']
Length: 3, dtype: str

In [116]:
experience_unique = df['experience'].unique()
print(experience_unique)

<ArrowStringArray>
['0', '5-10', '0-1', '1-5', '15+']
Length: 5, dtype: str

In [117]:
df.to_csv("C:\Portfolio-Projects\Job-Description-Analysis\data\clean\cleaned_job_descriptions.csv", index=False)

<>:1: SyntaxWarning: "\P" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\P"? A raw string is also an option.
<>:1: SyntaxWarning: "\P" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\P"? A raw string is also an option.
C:\Users\Akshay\AppData\Local\Temp\ipykernel_13908\2088954097.py:1: SyntaxWarning: "\P" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\P"? A raw string is also an option.
  df.to_csv("C:\Portfolio-Projects\Job-Description-Analysis\data\clean\cleaned_job_descriptions.csv", index=False)