### Data Engineering

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(r"C:\Portfolio-Projects\Job-Description-Analysis\data\clean\cleaned_job_descriptions.csv")

In [3]:
df.head(10)

,id,role,type,job_desc,year,qualification,experience,tech_skills,soft_skills
0,1,AI Engineer,Internship,"Final year students / recent graduates in CS, ...",2026,Bachelors,0,"Python, ML, LangChain, Hugging Face, OpenAI API","Communication, Problem Solving"
1,2,AI Engineer,Internship,Proficiency in Python and comfort working with...,2026,Bachelors,0,"Python, APIs, LLMs, Prompt Engineering, LangCh...","Communication, Problem Solving"
2,3,AI Engineer,Internship,Strong interest in AI and a willingness to lea...,2026,Bachelors,0,"Python, Javascript, React, Full Stack, APIs, M...","Communication, Problem Solving"
3,4,AI Engineer,Senior,6+ years full-stack software engineering exper...,2026,Not Specified,5-10,"Python, Javascript, React, Full Stack, SQL, AP...","Communication, Problem Solving"
4,5,AI Engineer,Junior,"AI/ML models, Python, Core ML concepts, ML fra...",2026,Bachelors,0-1,"Python, ML, TensorFlow/PyTorch, Scikit-Learn, ...","Communication, Problem Solving"
5,6,AI Engineer,Junior,4–5 years of proven development experience in ...,2026,Bachelors,5-10,"Python, C++, Java, TensorFlow/PyTorch, vLLM, O...","Communication, Problem Solving"
6,7,AI Engineer,Senior,5-10 years overall experience\n3+ years of han...,2026,Not Specified,5-10,"Python, SQL, PowerBI, SAP, LLMs, Prompt Engine...","Communication, Problem Solving"
7,8,AI Engineer,Junior,Proficiency in C/C++ and python programming\nH...,2026,Bachelors,0-1,"Python, C, C++, Sytem Design, Model Evaluation","Communication, Problem Solving"
8,9,AI Engineer,Internship,Python\nMachine Learning Fundamentals\nLarge L...,2026,Bachelors,0,"Python, ML, LLMs, Prompt Engineering, APIs, La...","Communication, Problem Solving"
9,10,AI Engineer,Internship,"Solid understanding of LLMs, tokenization, tra...",2026,Bachelors,0,"Python, Pandas, NumPyHugging Face, LangChain, ...","Communication, Problem Solving"

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 165 entries, 0 to 164
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             165 non-null    int64
 1   role           165 non-null    str
 2   type           165 non-null    str
 3   job_desc       165 non-null    str
 4   year           165 non-null    int64
 5   qualification  165 non-null    str
 6   experience     165 non-null    str
 7   tech_skills    165 non-null    str
 8   soft_skills    165 non-null    str
dtypes: int64(2), str(7)
memory usage: 11.7 KB

In [5]:
df_intern = df[df['type'].eq('Internship')]
df_intern.head(10)

,id,role,type,job_desc,year,qualification,experience,tech_skills,soft_skills
0,1,AI Engineer,Internship,"Final year students / recent graduates in CS, ...",2026,Bachelors,0,"Python, ML, LangChain, Hugging Face, OpenAI API","Communication, Problem Solving"
1,2,AI Engineer,Internship,Proficiency in Python and comfort working with...,2026,Bachelors,0,"Python, APIs, LLMs, Prompt Engineering, LangCh...","Communication, Problem Solving"
2,3,AI Engineer,Internship,Strong interest in AI and a willingness to lea...,2026,Bachelors,0,"Python, Javascript, React, Full Stack, APIs, M...","Communication, Problem Solving"
8,9,AI Engineer,Internship,Python\nMachine Learning Fundamentals\nLarge L...,2026,Bachelors,0,"Python, ML, LLMs, Prompt Engineering, APIs, La...","Communication, Problem Solving"
9,10,AI Engineer,Internship,"Solid understanding of LLMs, tokenization, tra...",2026,Bachelors,0,"Python, Pandas, NumPyHugging Face, LangChain, ...","Communication, Problem Solving"
12,13,AI Developer,Internship,Basic to intermediate Python programming skill...,2026,Bachelors,0,"Python, ML, GenAI, APIs, Git, Prompt Engineeri...","Communication, Problem Solving, Analytical Skills"
25,27,AI Engineer,Internship,Python Skills: You should be very comfortable ...,2026,Bachelors,0,"Python, Javascript, React, LLMs, VectorDB, Lan...","Communication, Problem Solving"
26,28,AI Engineer,Internship,Exposure to Full-Stack Development (frontend a...,2026,Bachelors,0,"Python, Git, Github, Full Stack, LLMs, APIs, G...","Communication, Problem Solving, Analytical Skills"
27,29,AI Engineer,Internship,"Python, TensorFlow, PyTorch, Scikit-learn, Num...",2026,Bachelors,0,"Python, TensorFlow/PyTorch, Scikit-Learn, NumP...","Communication, Problem Solving"
28,30,AI Engineer,Internship,Recently completed a degree in Computer Scienc...,2026,Bachelors,0,"Python, GenAI, LLMs, RAG, Prompt Engineering, ...","Communication, Problem Solving, Analytical Skills"

In [6]:
df_intern.info()

<class 'pandas.DataFrame'>
Index: 55 entries, 0 to 164
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             55 non-null     int64
 1   role           55 non-null     str
 2   type           55 non-null     str
 3   job_desc       55 non-null     str
 4   year           55 non-null     int64
 5   qualification  55 non-null     str
 6   experience     55 non-null     str
 7   tech_skills    55 non-null     str
 8   soft_skills    55 non-null     str
dtypes: int64(2), str(7)
memory usage: 4.3 KB

In [7]:
df_intern = df_intern[df_intern['qualification'].eq('Bachelors')]
df_intern.head(10)

,id,role,type,job_desc,year,qualification,experience,tech_skills,soft_skills
0,1,AI Engineer,Internship,"Final year students / recent graduates in CS, ...",2026,Bachelors,0,"Python, ML, LangChain, Hugging Face, OpenAI API","Communication, Problem Solving"
1,2,AI Engineer,Internship,Proficiency in Python and comfort working with...,2026,Bachelors,0,"Python, APIs, LLMs, Prompt Engineering, LangCh...","Communication, Problem Solving"
2,3,AI Engineer,Internship,Strong interest in AI and a willingness to lea...,2026,Bachelors,0,"Python, Javascript, React, Full Stack, APIs, M...","Communication, Problem Solving"
8,9,AI Engineer,Internship,Python\nMachine Learning Fundamentals\nLarge L...,2026,Bachelors,0,"Python, ML, LLMs, Prompt Engineering, APIs, La...","Communication, Problem Solving"
9,10,AI Engineer,Internship,"Solid understanding of LLMs, tokenization, tra...",2026,Bachelors,0,"Python, Pandas, NumPyHugging Face, LangChain, ...","Communication, Problem Solving"
12,13,AI Developer,Internship,Basic to intermediate Python programming skill...,2026,Bachelors,0,"Python, ML, GenAI, APIs, Git, Prompt Engineeri...","Communication, Problem Solving, Analytical Skills"
25,27,AI Engineer,Internship,Python Skills: You should be very comfortable ...,2026,Bachelors,0,"Python, Javascript, React, LLMs, VectorDB, Lan...","Communication, Problem Solving"
26,28,AI Engineer,Internship,Exposure to Full-Stack Development (frontend a...,2026,Bachelors,0,"Python, Git, Github, Full Stack, LLMs, APIs, G...","Communication, Problem Solving, Analytical Skills"
27,29,AI Engineer,Internship,"Python, TensorFlow, PyTorch, Scikit-learn, Num...",2026,Bachelors,0,"Python, TensorFlow/PyTorch, Scikit-Learn, NumP...","Communication, Problem Solving"
28,30,AI Engineer,Internship,Recently completed a degree in Computer Scienc...,2026,Bachelors,0,"Python, GenAI, LLMs, RAG, Prompt Engineering, ...","Communication, Problem Solving, Analytical Skills"

In [8]:
df_intern.info()

<class 'pandas.DataFrame'>
Index: 54 entries, 0 to 164
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             54 non-null     int64
 1   role           54 non-null     str
 2   type           54 non-null     str
 3   job_desc       54 non-null     str
 4   year           54 non-null     int64
 5   qualification  54 non-null     str
 6   experience     54 non-null     str
 7   tech_skills    54 non-null     str
 8   soft_skills    54 non-null     str
dtypes: int64(2), str(7)
memory usage: 4.2 KB

In [9]:
df_intern.to_csv(r"C:\Portfolio-Projects\Job-Description-Analysis\data\clean\cleaned_job_descriptions_internships.csv", index=False)

In [10]:
df_junior = df[df['type'].eq('Junior')]
df_junior.head(10)

,id,role,type,job_desc,year,qualification,experience,tech_skills,soft_skills
4,5,AI Engineer,Junior,"AI/ML models, Python, Core ML concepts, ML fra...",2026,Bachelors,0-1,"Python, ML, TensorFlow/PyTorch, Scikit-Learn, ...","Communication, Problem Solving"
5,6,AI Engineer,Junior,4–5 years of proven development experience in ...,2026,Bachelors,5-10,"Python, C++, Java, TensorFlow/PyTorch, vLLM, O...","Communication, Problem Solving"
7,8,AI Engineer,Junior,Proficiency in C/C++ and python programming\nH...,2026,Bachelors,0-1,"Python, C, C++, Sytem Design, Model Evaluation","Communication, Problem Solving"
13,14,AI Engineer,Junior,"Basic understanding of AI, Machine Learning, o...",2026,Bachelors,0-1,"Python, ML, APIs","Communication, Problem Solving"
15,16,AI Engineer,Junior,Docker / Containerization\nAWS / Azure / GCP e...,2026,Bachelors,0-1,"Python, ML, Docker, AWS/Azure,","Communication, Problem Solving"
16,17,AI Engineer,Junior,"1+ years of experience in AI, LLMs, automation...",2026,Bachelors,1-5,"Python, APIs, LLMs, Prompt Engineering, LangCh...","Communication, Problem Solving, Ownership"
17,18,AI Developer,Junior,Strong Python programming\nExperience with Fas...,2026,Bachelors,0-1,"Python, React, Javascript, APIs, AWS/Azure, LL...","Communication, Problem Solving"
18,19,AI Engineer,Junior,"Degree in Computer Science, AI, or a related f...",2026,Bachelors,0-1,"Python, Javascript, LLMs, Prompt Engineering,...","Communication, Problem Solving"
21,22,AI Engineer,Junior,Strong programming skills in Python.\nExperien...,2026,Bachelors,0-1,"Python, LLMs, Prompt Engineering, RAG, TensorF...","Communication, Problem Solving"
24,26,AI Engineer,Junior,Strong hands-on experience in Python programmi...,2026,Bachelors,0-1,"Python, APIs, GenAI, LLMs, Pandas, NumPy, Scik...","Communication, Problem Solving"

In [11]:
df_junior.info()

<class 'pandas.DataFrame'>
Index: 55 entries, 4 to 142
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             55 non-null     int64
 1   role           55 non-null     str
 2   type           55 non-null     str
 3   job_desc       55 non-null     str
 4   year           55 non-null     int64
 5   qualification  55 non-null     str
 6   experience     55 non-null     str
 7   tech_skills    55 non-null     str
 8   soft_skills    55 non-null     str
dtypes: int64(2), str(7)
memory usage: 4.3 KB

In [12]:
df_junior.to_csv(r"C:\Portfolio-Projects\Job-Description-Analysis\data\clean\cleaned_job_descriptions_junior.csv", index=False)

In [13]:
df_senior = df[df['type'].eq('Senior')]
df_senior.head(15)

,id,role,type,job_desc,year,qualification,experience,tech_skills,soft_skills
3,4,AI Engineer,Senior,6+ years full-stack software engineering exper...,2026,Not Specified,5-10,"Python, Javascript, React, Full Stack, SQL, AP...","Communication, Problem Solving"
6,7,AI Engineer,Senior,5-10 years overall experience\n3+ years of han...,2026,Not Specified,5-10,"Python, SQL, PowerBI, SAP, LLMs, Prompt Engine...","Communication, Problem Solving"
10,11,AI Engineer,Senior,4–6 years of experience in Data Science / Mach...,2026,Not Specified,5-10,"Python, Scikit-Learn, Pandas, NumPy, ML, LLMs,...","Communication, Problem Solving"
11,12,AI Engineer,Senior,Bachelor's or Master's degree in Computer Scie...,2026,Bachelors/Masters,1-5,"Python, ML, APIs, GenAI, LangChain, LangGraph,...","Communication, Problem Solving, Analytical Skills"
14,15,AI Engineer,Senior,4–6 years of experience in Data Science / Mach...,2026,Not Specified,5-10,"Python, ML, Pandas, NumPy, Scikit-Learn, GenAI...","Communication, Problem Solving"
19,20,AI Engineer,Senior,Proven track record with at least 5 years of e...,2026,Not Specified,1-5,"Python, ML, NLP, MLOps, Feature Engineering, A...","Communication, Problem Solving"
20,21,AI Engineer,Senior,5+ years overall experience in software develo...,2026,Not Specified,5-10,"Python, APIs, LLMs, Prompt Engineering, LangCh...","Communication, Problem Solving"
22,24,AI Developer,Senior,Core Software Engineering (Required)\nStrong h...,2026,Not Specified,5-10,"Python, Javascript, AWS/Azure, VectorDB, LLMs,...","Communication, Problem Solving"
23,25,AI Engineer,Senior,15+ years of overall IT experience\nStrong exp...,2026,Not Specified,15+,"Python, ML, APIs, AWS/Azure, CI/CD, Github, Git,","Communication, Problem Solving"
29,31,AI Developer,Senior,trong hands-on experience in Python backend de...,2026,Bachelors,5-10,"Python, LangChain, LangGraph, CrewAI, AutoGen,...","Communication, Problem Solving"
30,32,AI Developer,Senior,To qualify for the role you must have B.E/ B.T...,2026,Masters,5-10,"Python, ML, AWS/Azure, SQL, Docker, Kubernete...","Communication, Problem Solving"
31,33,AI Developer,Senior,• 3–6 years of software development experience...,2026,Not Specified,5-10,"Python, APIs, SQL, LLMs, Prompt Engineering, R...","Communication, Problem Solving"
32,34,AI Engineer,Senior,- Experience in publishing research or contrib...,2026,Masters,5-10,"Python, GenAI, LLMs","Communication, Problem Solving"
40,42,AI Engineer,Senior,Python · JS/TS · Neo4j/Cypher · MongoDB · Post...,2026,Not Specified,1-5,"Python, Javascript, SQL, LLMs, APIs, VectorDB,...","Communication, Problem Solving"
42,44,AI Engineer,Senior,You will focus on creating reusable agent arch...,2026,Not Specified,5-10,"Python, ML, APIs, LLMs, LangChain, LangGraph, ...","Communication, Problem Solving"

In [14]:
df_senior.info()

<class 'pandas.DataFrame'>
Index: 55 entries, 3 to 109
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             55 non-null     int64
 1   role           55 non-null     str
 2   type           55 non-null     str
 3   job_desc       55 non-null     str
 4   year           55 non-null     int64
 5   qualification  55 non-null     str
 6   experience     55 non-null     str
 7   tech_skills    55 non-null     str
 8   soft_skills    55 non-null     str
dtypes: int64(2), str(7)
memory usage: 4.3 KB

In [15]:
df_senior.to_csv(r"C:\Portfolio-Projects\Job-Description-Analysis\data\clean\cleaned_job_descriptions_senior.csv", index=False)

In [16]:
df_dev = df[df['role'].eq('AI Developer')]
df_dev.head(10)

,id,role,type,job_desc,year,qualification,experience,tech_skills,soft_skills
12,13,AI Developer,Internship,Basic to intermediate Python programming skill...,2026,Bachelors,0,"Python, ML, GenAI, APIs, Git, Prompt Engineeri...","Communication, Problem Solving, Analytical Skills"
17,18,AI Developer,Junior,Strong Python programming\nExperience with Fas...,2026,Bachelors,0-1,"Python, React, Javascript, APIs, AWS/Azure, LL...","Communication, Problem Solving"
22,24,AI Developer,Senior,Core Software Engineering (Required)\nStrong h...,2026,Not Specified,5-10,"Python, Javascript, AWS/Azure, VectorDB, LLMs,...","Communication, Problem Solving"
29,31,AI Developer,Senior,trong hands-on experience in Python backend de...,2026,Bachelors,5-10,"Python, LangChain, LangGraph, CrewAI, AutoGen,...","Communication, Problem Solving"
30,32,AI Developer,Senior,To qualify for the role you must have B.E/ B.T...,2026,Masters,5-10,"Python, ML, AWS/Azure, SQL, Docker, Kubernete...","Communication, Problem Solving"
31,33,AI Developer,Senior,• 3–6 years of software development experience...,2026,Not Specified,5-10,"Python, APIs, SQL, LLMs, Prompt Engineering, R...","Communication, Problem Solving"
33,35,AI Developer,Junior,"Strong foundation in Java, React, NodeJS, Pyth...",2026,Bachelors,0-1,"Java, React, NodeJS, Python, SQL, Excel, Pand...","Problem Solving, Strong analytical, logical th..."
47,49,AI Developer,Internship,1. Building event-driven automations to captur...,2026,Bachelors,0,"Python, LLMs, ML, APIs, n8n, GenAI","Communication, Problem Solving"
48,50,AI Developer,Internship,• Currently pursuing a bachelor's or master's ...,2026,Bachelors,0,"Python, LLMs, GenAI, ML, Agents","Communication, Problem Solving"
49,51,AI Developer,Internship,• Basic knowledge of Python programming.\n• Un...,2026,Bachelors,0,"Python, ML, GenAI, LLMs, NLP, APIs, TensorFlow...","Communication, Problem Solving"